server:
  port: 8003
spring:
  application:
    name: moto-service
  jpa:
    show-sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    intance:
      hostname: localhost
